### ISSUE TITLE
Crash at Title Screen

### ISSUE THREAD

**Issue by Dumpling00** [CircuitLord/ReactiveMusic#11] opened 2024-07-05 10:58 UTC
Hello! Been using Reactive Music for a long while now, love it. I'm on Fabric 1.20.1 and I've had this issue when updating the mod to version 2.0 but didn't report it expecting a hotfix to come out soon thinking maybe I wasn't the only one. So when I saw version 3.0 I tried again but I'm getting the same issue. Not sure what changes in the code, but Version 1.0 works flawlessly. Here's what the log has to say.

![image](https://github.com/CircuitLord/ReactiveMusic/assets/44829013/cb431983-39fe-41d5-9516-24c65a62928d)

Hopefully this helps. Thank you for your time and consideration.

**Comment by GrigoryiAI** [comment] 2024-07-05 15:30
Same problem, for me it appears on Fabric API 0.92.2 in Prominence II RPG modpack. With Fabric API 0.92.1, everything works.
![image](https://github.com/CircuitLord/ReactiveMusic/assets/116576185/a80d2d6e-9540-420f-8763-8713a32da37e)

**Comment by CircuitLord** [comment] 2024-07-10 03:39
It looks like the error is something related to it not finding a valid audio device, not exactly sure what would be going wrong there but I'll look into it!

**Comment by CircuitLord** [comment] 2024-07-10 03:57
@GrigoryiAI I just tested Prominence II RPG with both fabric 0.91 and 0.92 and it worked with both, it doesn't seem to be immediately compatible because there's some other music mod in that pack that's trying to play at the same time but I wasn't able to reproduce the crash

I'll see if I'm able to put in a theoretical fix but if you have any more information about it that may be helpful

**Comment by GrigoryiAI** [comment] 2024-07-10 17:57
![image](https://github.com/CircuitLord/ReactiveMusic/assets/116576185/102acf5f-15a6-4234-8c83-14118992fe07)
The problem was with last version of ad astra or Resourseful Lib, idk. So I downgraded them, now everything works. Thanks for the great mod! Mods on the screen crashes with same error.

**Comment by CircuitLord** [comment] 2024-07-10 23:32
Gotcha, I'll give it another shot tonight with those mods specifically and see if I can repro it!

**Comment by skellitor301** [comment] 2024-07-12 19:16
I had a similar issue to what GregoryAI had with the same error. I went to apply the solution presented but the mods shown match versions to what I have and it still crashed.
Crashlog: https://mclo.gs/DaxpqJ1
Full log: https://mclo.gs/KGP7wEB

**Comment by CircuitLord** [comment] 2024-09-12 06:27
This should be fixed as of v0.3.1, let me know if you have any issues!

**Closed by CircuitLord** 2024-09-12 06:27 UTC
